# Generated by Django 4.2.13 on 2024-06-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_secret',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
