# Generated by Django 4.2.13 on 2024-06-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_secret',
            field=models.CharField(max_length=32),
        ),
    ]
