# Generated by Django 4.2.17 on 2025-01-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_session_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='enable_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
