# Generated by Django 4.2.17 on 2025-01-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_enable_2fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='enable_2fa',
            field=models.BooleanField(default=False, verbose_name='Enable 2FA'),
        ),
    ]
