# Generated by Django 4.2.17 on 2025-01-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_enable_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='encryption_salt',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
