# Generated by Django 4.2.18 on 2025-02-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_encryption_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allow_account_notifications',
            field=models.BooleanField(default=True, verbose_name='Allow Account Notifications'),
        ),
    ]
