# Generated by Django 4.2.18 on 2025-02-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_allow_account_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allow_master_password_update_notifications',
            field=models.BooleanField(default=True, verbose_name='Allow Master Password Update Notifications'),
        ),
    ]
