# Generated by Django 4.2.18 on 2025-02-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_allow_master_password_update_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='allow_account_notifications',
        ),
        migrations.AddField(
            model_name='customuser',
            name='allow_account_update_notifications',
            field=models.BooleanField(default=True, verbose_name='Allow Account Update Notifications'),
        ),
    ]
