# Generated by Django 6.0.5 on 2026-05-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_allow_account_update_notifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='allow_account_update_notifications',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='allow_master_password_update_notifications',
        ),
    ]
