services:
  app:
    build: .
    container_name: passmanagerweb
    command: gunicorn --bind 0.0.0.0:8000 main.wsgi:application
    volumes:
      - .:/app
    ports:
      - "${PORT:-8000}:8000"
    env_file:
      - main/.env
