services:
  django-web:
    build: .
    container_name: django-docker
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - main/.env
    restart: unless-stopped

  frontend-proxy:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static:ro
    depends_on:
      - django-web
    restart: unless-stopped

volumes:
  static_volume:
