[project]
name = "passmanagerweb"
version = "0.1.0"
description = "Self-hosted password manager for secure online credentials."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crispy-bootstrap5==2026.3",
    "cryptography==50.0.0",
    "dj-database-url==3.1.2",
    "django==6.0.7",
    "django-axes[ipware]>=8.3.1",
    "django-crispy-forms==2.7",
    "gunicorn==26.0.0",
    "psycopg2-binary==2.9.12",
    "pyotp==2.9.0",
    "python-dotenv==1.2.3",
    "qrcode[pil]>=8.2",
    "requests>=2.34.2",
    "uvicorn==0.49.0",
    "whitenoise[brotli]>=6.12.0",
    "zxcvbn>=4.5.0",
]

[dependency-groups]
dev = [
    "django-extensions>=4.1",
    "pydotplus>=2.0.2",
]
