# Generated by Django 6.0.5 on 2026-05-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0011_remove_item_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='url',
            new_name='domain',
        ),
    ]
