# Generated by Django 4.2.15 on 2024-12-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passmanager', '0004_rename_website_item_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(max_length=100),
        ),
    ]
