# Generated by Django 4.2.15 on 2024-12-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passmanager', '0006_alter_item_name_alter_item_notes_alter_item_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(max_length=50),
        ),
    ]
