# Generated by Django 5.2.4 on 2025-08-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passmanager', '0007_alter_item_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='group',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
