# Generated by Django 5.2.6 on 2025-09-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passmanager', '0009_alter_item_notes_alter_item_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
