# Generated by Django 6.0.5 on 2026-05-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passmanager', '0010_alter_item_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='group',
        ),
    ]
